os: Visual Studio 2015

environment:
  matrix:
    - PY_MAJOR_VER: 2
      PYTHON_ARCH: "x86"
    - PY_MAJOR_VER: 2
      PYTHON_ARCH: "x86_64"
    - PY_MAJOR_VER: 3
      PYTHON_ARCH: "x86"
    - PY_MAJOR_VER: 3
      PYTHON_ARCH: "x86_64"

matrix:
  fast_finish: true

install:
  - "python -m pip install flake8"

build: off

test_script:
  - "flake8"
  - "python setup.py test"
