coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
        if_ci_failed: error
    patch:
      default:
        # basic
        target: auto
        threshold: 5%
        if_ci_failed: error
