#!/../bin/bash

# if you change data/full_example.py 
# you should rerun this script to update the output files
# for testing purposes.

python ../bin/pdb_chain.py data/full_example.pdb > output/output_pdb_chain_1.pdb
python ../bin/pdb_chain.py -Z data/full_example.pdb > output/output_pdb_chain_2.pdb
python ../bin/pdb_chainxseg.py data/full_example.pdb > output/output_pdb_chainxseg_1.pdb
python ../bin/pdb_delatom.py data/full_example.pdb > output/output_pdb_delatom_1.pdb
python ../bin/pdb_delatom.py -S data/full_example.pdb > output/output_pdb_delatom_2.pdb
python ../bin/pdb_delchain.py -A data/full_example.pdb > output/output_pdb_delchain_1.pdb
python ../bin/pdb_delchain.py -AG data/full_example.pdb > output/output_pdb_delchain_2.pdb
python ../bin/pdb_delsc.py data/full_example.pdb > output/output_pdb_delsc_1.pdb
python ../bin/pdb_delsc.py -0:13 data/full_example.pdb > output/output_pdb_delsc_2.pdb
python ../bin/pdb_element.py data/full_example.pdb > output/output_pdb_element_1.pdb
python ../bin/pdb_keepcoord.py data/full_example.pdb > output/output_pdb_keepcoord_1.pdb
python ../bin/pdb_merge.py data/full_example.pdb data/nano.pdb > output/output_pdb_merge_1.pdb
python ../bin/pdb_occ.py -0.5 data/full_example.pdb > output/output_pdb_occ_1.pdb
python ../bin/pdb_occ.py -2 data/full_example.pdb > output/output_pdb_occ_2.pdb
python ../bin/pdb_reres.py data/full_example.pdb > output/output_pdb_reres_1.pdb
python ../bin/pdb_reres.py -50 data/full_example.pdb > output/output_pdb_reres_2.pdb
python ../bin/pdb_reres.py --50 data/full_example.pdb > output/output_pdb_reres_3.pdb
python ../bin/pdb_rplchain.py data/full_example.pdb > output/output_pdb_rplchain_1.pdb
python ../bin/pdb_rplchain.py -G:Z data/full_example.pdb > output/output_pdb_rplchain_2.pdb
python ../bin/pdb_seg.py data/full_example.pdb > output/output_pdb_seg_1.pdb
python ../bin/pdb_seg.py -T data/full_example.pdb > output/output_pdb_seg_2.pdb
python ../bin/pdb_segxchain.py data/full_example.pdb > output/output_pdb_segxchain_1.pdb
python ../bin/pdb_selchain.py -A data/full_example.pdb > output/output_pdb_selchain_1.pdb
python ../bin/pdb_selchain.py -G data/full_example.pdb > output/output_pdb_selchain_2.pdb
python ../bin/pdb_selres.py -1:3 data/full_example.pdb > output/output_pdb_selres_1.pdb
python ../bin/pdb_selres.py -64: data/full_example.pdb > output/output_pdb_selres_2.pdb
python ../bin/pdb_selres.py -:3 data/full_example.pdb > output/output_pdb_selres_3.pdb
python ../bin/pdb_selres.py -::5 data/full_example.pdb > output/output_pdb_selres_4.pdb
python ../bin/pdb_selres.py -40:60:5 data/full_example.pdb > output/output_pdb_selres_5.pdb
python ../bin/pdb_shiftres.py -50 data/full_example.pdb > output/output_pdb_shiftres_1.pdb
python ../bin/pdb_shiftres.py --10 data/full_example.pdb > output/output_pdb_shiftres_2.pdb
python ../bin/pdb_splitchain.py data/full_example.pdb
mv full_example_* output/
python ../bin/pdb_splitmodel.py data/nano_2_models.pdb
mv nano_2_models_* output/
python ../bin/pdb_splitseg.py data/full_example.pdb
mv full_example_* output/
python ../bin/pdb_striphet.py data/full_example.pdb > output/output_pdb_striphet_1.pdb
python ../bin/pdb_wc.py data/full_example.pdb > output/output_wc_1.txt
python ../bin/pdb_wc.py -m data/full_example.pdb > output/output_wc_2.txt
python ../bin/pdb_wc.py -r data/full_example.pdb > output/output_wc_3.txt
python ../bin/pdb_wc.py -c data/full_example.pdb > output/output_wc_4.txt
python ../bin/pdb_wc.py -a data/full_example.pdb > output/output_wc_5.txt
python ../bin/pdb_wc.py -h data/full_example.pdb > output/output_wc_6.txt
python ../bin/pdb_wc.py -o data/full_example.pdb > output/output_wc_7.txt
python ../bin/pdb_wc.py -i data/full_example.pdb > output/output_wc_8.txt
python ../bin/pdb_wc.py -g data/full_example.pdb > output/output_wc_9.txt
python ../bin/pdb_rplresname.py -MET:FOO data/full_example.pdb > output/output_pdb_rplresname_1.pdb